select
    order_id,
    order_number,
    customer_id,
    order_date,
    order_status,
    channel,
    country_code,
    delivery_address_city as city,
    delivery_address_region as region,
    delivery_address_zone as zone,
    promo_code,
    currency,
    subtotal_amount,
    shipping_amount,
    discount_amount,
    total_amount,
    captured_amount,
    has_payment,
    is_partial_payment,
    customer_dq_flag,
    order_year_month,
    created_at,
    updated_at
from {{ source('curated', 'orders') }}
